"""Markdown report assembly. Pulls from the same analysis functions the CLI uses."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from powermet import __version__
from powermet.config import Config, Project
from powermet.correlation import be_correlations, pearson, strength_word
from powermet.errors import STAGES, analyze_errors, build_trend
from powermet.modeling import MODEL_NAMES, MODEL_ORDER, best_model_key, improvement_pct, latest_model_metadata, load
from powermet.selection import DatasetSlice, default_value, latest_build, latest_build_per_design
from powermet.schema import label
from powermet.storage import import_history, load_table, sanitized_path
from powermet.summary import compare_stages_text, summarize
from powermet.textfmt import fmt_int, fmt_mw, fmt_pct, fmt_r
from powermet.validation import validate
from powermet.visualization import CHARTS, make_charts, plots_available

REPORT_NAME = "power_metrology_report.md"


def _md_table(headers: list[str], rows: list[list]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def _metrics_row(name: str, m: dict) -> list[str]:
    return [name, fmt_pct(m.get("mape")), fmt_pct(m.get("p50_ape")), fmt_pct(m.get("p95_ape")),
            f"{m.get('mae', np.nan):.1f}", fmt_r(m.get("r2"))]


def build_report(project: Project, cfg: Config, df: pd.DataFrame, make_plots: bool = True) -> str:
    s = summarize(df)
    ea_p = analyze_errors(df, "physical", top_n=cfg.top_n_errors)
    ea_l = analyze_errors(df, "logical", top_n=cfg.top_n_errors)
    be_assoc = be_correlations(df)
    meta = latest_model_metadata(project)
    history = import_history(project)
    rep = validate(df.drop(columns=[c for c in df.columns if c.endswith("_error_mw") or c.endswith("_error_pct")
                                    or c.endswith("_ratio") or c == "wire_cap_fraction"], errors="ignore"))

    charts: list[Path] = []
    if make_plots and plots_available():
        stats = {"logical_r2": s.logical.get("r2"), "physical_r2": s.physical.get("r2"),
                 "wire_cap_r": next((a.r for a in ea_p.assoc_pct if a.x == "wire_cap_pf"), None)}
        charts = make_charts(df, project.reports_dir, stats)
    chart_names = {c.name for c in charts}

    def img(name: str, caption: str) -> str:
        return f"![{caption}]({name})" if name in chart_names else f"_{caption}: chart not generated (matplotlib unavailable or plots disabled)._"

    L: list[str] = []
    L.append("# Power Metrology Report")
    L.append("")
    L.append(f"Generated by powermet {__version__} on {pd.Timestamp.now('UTC').strftime('%Y-%m-%d %H:%M UTC')}.  ")
    L.append(f"Project: `{project.root}`  ")
    L.append("Question: **How well does FE power predict BE power, and which physical characteristics are associated with the difference?**")
    L.append("")

    # 1 dataset summary
    L.append("## 1. Dataset summary")
    L.append("")
    L.append(_md_table(["Item", "Value"], [
        ["Designs", fmt_int(s.n_designs) + (" (" + ", ".join(s.designs) + ")" if s.designs else "")],
        ["Builds (design x build)", fmt_int(s.n_builds)],
        ["FUBs (design x FUB)", fmt_int(s.n_fubs)],
        ["Measurements", fmt_int(s.n_rows)],
        ["BE power mean / median / P95", f"{fmt_mw(s.be_stats['mean'])} / {fmt_mw(s.be_stats['median'])} / {fmt_mw(s.be_stats['p95'])}"],
        ["BE power range", f"{fmt_mw(s.be_stats['min'])} .. {fmt_mw(s.be_stats['max'])}"],
    ]))
    L.append("")
    if history:
        L.append("Provenance (imports):")
        L.append("")
        L.append(_md_table(["Source file", "SHA-256", "Rows imported", "Rows rejected", "Imported at"],
                           [[h["source_file"], h["sha256"][:12], h["rows_imported"], h["rows_rejected"], h["imported_at"]] for h in history]))
        L.append("")

    # 2 data quality
    L.append("## 2. Data quality")
    L.append("")
    L.append(f"Validation of the processed dataset: {fmt_int(rep.n_rows)} rows, {fmt_int(rep.n_errors)} with errors, {fmt_int(rep.n_warnings)} with warnings.")
    if rep.issues:
        L.append("")
        L.append(_md_table(["Level", "Rows", "Issue"], [[i.level, "all" if i.column_level else i.count, i.message] for i in rep.issues]))
    if s.missing_features:
        L.append("")
        L.append("Missing feature values: " + ", ".join(f"{label(k)} ({v})" for k, v in s.missing_features.items()))
    if history and any(h["rows_rejected"] for h in history):
        L.append("")
        L.append(f"Rows rejected at import are kept in `{cfg.rejected}` with a `reject_reason` column.")
    L.append("")

    # 3/4 FE -> BE correlation
    for num, stage, ea in (("3", "logical", ea_l), ("4", "physical", ea_p)):
        name = STAGES[stage][3]
        m = ea.metrics
        r, _, _ = pearson(df[STAGES[stage][0]], df["be_mw"])
        L.append(f"## {num}. {name} -> BE correlation")
        L.append("")
        L.append(_md_table(["Metric", "Value"], [
            ["Pearson r", fmt_r(r)],
            ["R^2 (of BE = FE, no fit)", fmt_r(m.get("r2"))],
            ["Mean error (BE - FE) / BE", fmt_pct(-m.get("mean_error_pct", np.nan), signed=True)],
            ["MAPE", fmt_pct(m.get("mape"))],
            ["P50 / P95 |error|", f"{fmt_pct(m.get('p50_ape'))} / {fmt_pct(m.get('p95_ape'))}"],
            ["n", fmt_int(m.get("n"))],
        ]))
        L.append("")
        L.append(img(f"fe_{stage}_vs_be.png", f"{name} vs BE"))
        L.append("")
        bias = -m.get("mean_error_pct", np.nan)
        L.append(f"Interpretation: {name} power is {strength_word(r)} associated with BE power (r={fmt_r(r)}) "
                 f"and {'underestimates' if bias > 0 else 'overestimates'} it by {fmt_pct(abs(bias))} on average.")
        L.append("")

    # 5 error analysis
    L.append("## 5. Error analysis (FE physical -> BE)")
    L.append("")
    L.append("Largest errors by percentage:")
    L.append("")
    tp = ea_p.top_pct
    L.append(_md_table(["Design", "Build", "FUB", "FE (mW)", "BE (mW)", "Error"],
                       [[r["design"], r["build"], r["fub"], f"{r['fe_physical_mw']:.1f}", f"{r['be_mw']:.1f}",
                         fmt_pct(r["physical_error_pct"], signed=True)] for _, r in tp.iterrows()]))
    L.append("")
    L.append("Association of physical features with percentage error (Pearson r; association, not cause):")
    L.append("")
    L.append(_md_table(["Feature", "r (% error)", "r (mW error)"],
                       [[label(a.x), fmt_r(a.r), fmt_r(next((b.r for b in ea_p.assoc_mw if b.x == a.x), np.nan))] for a in ea_p.assoc_pct]))
    L.append("")
    L.append(img("error_vs_wire_cap.png", "FE physical error vs wire cap"))
    L.append("")
    L.append("Error by build:")
    L.append("")
    L.append(_md_table(["Build", "n", "Mean error", "MAPE", "P95"],
                       [[r["build"], int(r["n"]), fmt_pct(r["mean_error_pct"], True), fmt_pct(r["mape"]), fmt_pct(r["p95_ape"])]
                        for _, r in ea_p.by_build.iterrows()]))
    L.append("")
    L.append(build_trend(ea_p.by_build)[1])
    L.append("")

    # 6 feature correlations
    L.append("## 6. Feature correlations with BE power")
    L.append("")
    L.append(_md_table(["Variable", "r", "R^2", "n"], [[label(a.x), fmt_r(a.r), fmt_r(a.r2), fmt_int(a.n)] for a in be_assoc]))
    L.append("")
    L.append(img("feature_correlations.png", "Feature correlation matrix"))
    L.append("")
    L.append("Features that scale with block size (area, cell count, capacitance) correlate with each other and with power; treat these as associations only.")
    L.append("")

    # 7-9 models
    if meta:
        mt = meta["metrics"]
        L.append("## 7. Model comparison")
        L.append("")
        L.append(f"Split strategy: **{meta['split_strategy']}**. Training builds: {', '.join(meta['train_builds'])} "
                 f"({fmt_int(meta['n_train'])} rows). Held-out builds: {', '.join(meta['test_builds'])} ({fmt_int(meta['n_test'])} rows).")
        L.append("")
        L.append(_md_table(["Model", "MAPE", "P50", "P95", "MAE (mW)", "R^2"],
                           [_metrics_row(MODEL_NAMES[k], mt[k]) for k in MODEL_ORDER if k in mt]))
        L.append("")
        for k in MODEL_ORDER:
            if k in meta["features"] and k != "baseline":
                L.append(f"- {MODEL_NAMES[k]} features: " + ", ".join(label(f) for f in meta["features"][k]))
        for n in meta.get("notes", []):
            L.append(f"- Note: {n}")
        L.append("")

        L.append("## 8. Model evaluation")
        L.append("")
        best = best_model_key(mt)
        base, bm = mt["baseline"], mt[best]
        rows = [["Best model", MODEL_NAMES[best]],
                ["Held-out MAPE", fmt_pct(bm.get("mape"))],
                ["Held-out P95 |error|", fmt_pct(bm.get("p95_ape"))],
                ["Held-out R^2", fmt_r(bm.get("r2"))],
                ["Baseline MAPE (BE = FE physical)", fmt_pct(base.get("mape"))],
                ["Improvement over baseline", fmt_pct(improvement_pct(base, bm))]]
        if "scaled" in mt:
            rows.append(["Scaled-baseline MAPE (bias correction only)", fmt_pct(mt["scaled"].get("mape"))])
            rows.append(["Improvement over scaled baseline", fmt_pct(improvement_pct(mt["scaled"], bm))])
        L.append(_md_table(["Item", "Value"], rows))
        L.append("")

        L.append("## 9. Feature importance")
        L.append("")
        imp = meta.get("feature_importance", {})
        key = "tree" if "tree" in imp else "linear" if "linear" in imp else None
        if key:
            L.append(f"Permutation importance of the {MODEL_NAMES[key]} model on held-out builds (share of MAPE increase when a feature is shuffled):")
            L.append("")
            L.append(_md_table(["Feature", "Share"], [[label(f), f"{v:.2f}"] for f, v in imp[key].items()]))
            L.append("")
        if meta.get("linear_std_coefficients"):
            L.append("Linear model: change in predicted BE (mW) per one standard deviation of each feature:")
            L.append("")
            L.append(_md_table(["Feature", "mW / sd"], [[label(f), f"{v:+.1f}"] for f, v in meta["linear_std_coefficients"].items()]))
            L.append("")
        L.append("Importance is model-specific evidence about this dataset, not proof of physical cause.")
        L.append("")
    else:
        for num, title in (("7", "Model comparison"), ("8", "Model evaluation"), ("9", "Feature importance")):
            L.append(f"## {num}. {title}")
            L.append("")
            L.append("_No trained model. Run `powermet model train`._")
            L.append("")

    # 10 key findings
    L.append("## 10. Key findings")
    L.append("")
    findings = [compare_stages_text(s)]
    if ea_p.assoc_pct:
        top = ea_p.assoc_pct[0]
        findings.append(f"The remaining FE physical -> BE percentage error is most associated with {label(top.x)} "
                        f"(r={fmt_r(top.r)}, {strength_word(top.r)} associated).")
    findings.append(build_trend(ea_p.by_build)[1])
    if meta:
        mt = meta["metrics"]
        best = best_model_key(mt)
        if best == "baseline":
            findings.append("No model beat the FE physical baseline on held-out builds; physical features did not add predictive value here.")
        else:
            findings.append(f"{MODEL_NAMES[best]} reduces held-out MAPE from {fmt_pct(mt['baseline'].get('mape'))} to "
                            f"{fmt_pct(mt[best].get('mape'))} ({fmt_pct(improvement_pct(mt['baseline'], mt[best]))} relative).")
            if "scaled" in mt:
                g = improvement_pct(mt["scaled"], mt[best])
                findings.append(f"Of that, a single scale factor on FE physical power accounts for most of the gain "
                                f"(scaled baseline MAPE {fmt_pct(mt['scaled'].get('mape'))}); physical features add a further "
                                f"{fmt_pct(g)} relative reduction." if g > 2 else
                                f"A single scale factor on FE physical power (MAPE {fmt_pct(mt['scaled'].get('mape'))}) captures "
                                f"nearly all of the gain; physical features add little beyond bias correction ({fmt_pct(g)}).")
    for f in findings:
        L.append(f"- {f}")
    L.append("")

    # 11 limitations
    L.append("## 11. Limitations")
    L.append("")
    for t in (
        "All relationships reported are statistical associations within this dataset; none establish physical cause.",
        "FUB is an analytical dimension; input data is assumed to be pre-mapped to FUBs and native FE/BE hierarchies are not reconciled here.",
        "Held-out builds are the *latest* builds, so metrics reflect extrapolation to newer builds; with few builds these metrics are noisy.",
        "Tree models cannot extrapolate beyond the training range of any feature; systematic build-to-build drift is not modeled explicitly.",
        "Percentage error is undefined where BE power is zero; such rows are rejected at import.",
        "Features that scale with block size are collinear, so individual coefficients and importances are not uniquely attributable.",
    ):
        L.append(f"- {t}")
    if meta and len(meta["train_builds"]) + len(meta["test_builds"]) < cfg.min_builds_warn:
        L.append(f"- Only {len(meta['train_builds']) + len(meta['test_builds'])} builds were available; treat model metrics as indicative only.")
    L.append("")

    # 12 next steps
    L.append("## 12. Next-step recommendations")
    L.append("")
    nxt = []
    if ea_p.assoc_pct:
        top = ea_p.assoc_pct[0]
        nxt.append(f"Test whether the {label(top.x)}-associated error persists across builds and designs (compare per-build r; see section 5).")
    slope, _ = build_trend(ea_p.by_build)
    if np.isfinite(slope) and abs(slope) > 0.5:
        nxt.append("Error drifts with build order; investigate what changes between builds (routing, clock tree, activity vectors) before trusting any single-build calibration.")
    nxt.append("Replace synthetic data with real FE/BE exports for one design and re-run the same workflow unchanged.")
    nxt.append("If a scale factor explains most of the gain, calibrate FE physical power per design/stage before adding models.")
    nxt.append("Add workload and operating-point coverage so the model is not tuned to one vector.")
    for t in nxt:
        L.append(f"- {t}")
    L.append("")
    L.extend(_v1_v3_sections(project, cfg, df, meta))
    L.extend(_timing_energy_sections(project, cfg, df, meta))
    L.extend(_closure_sections(project, cfg, df))
    return "\n".join(L)


def _closure_sections(project: Project, cfg: Config, df: pd.DataFrame) -> list[str]:
    """Budgets, power intent, qualification, hotspots."""
    from pathlib import Path

    L: list[str] = []
    L.append("## 25. Power budgets by milestone")
    L.append("")
    cands = [Path(cfg.budgets_file), project.root / "budgets.toml", *sorted(Path.cwd().glob("*/budgets.toml"))]
    bpath = next((c for c in cands if c.exists()), None)
    if bpath:
        try:
            from powermet.budgets import check_budgets, load_budgets
            from powermet.storage import load_dataset as _ld
            raw = _ld(project, cfg, raw=True)
            st = check_budgets(raw, load_budgets(bpath), lineage=load_table(project, "lineage"))
            from powermet.budgets import fmt_metric
            L.append(_md_table(["Design", "Scope", "Metric", "Build", "Milestone", "Target", "Actual", "FUBs", "Margin", "Trend", "Status"],
                               [[s_.budget.design, s_.budget.scope, s_.budget.short_metric, s_.build, s_.milestone,
                                 fmt_metric(s_.budget.target, s_.budget.metric), fmt_metric(s_.actual, s_.budget.metric),
                                 f"{s_.fubs_measured}/{s_.fubs_expected}" if s_.fubs_expected else str(s_.fubs_measured),
                                 fmt_pct(s_.margin_pct, True), fmt_pct(s_.trend_pct_per_build, True) + "/build" if np.isfinite(s_.trend_pct_per_build) else "n/a",
                                 s_.status + ("" if s_.complete else " (INCOMPLETE)")] for s_ in st]))
            L.append("")
            L.append("Budgets are checked against the raw dataset; INCOMPLETE marks scopes whose FUBs are not all measured, so the actual is an undercount.")
        except Exception as exc:
            L.append(f"_Budget check unavailable: {exc}_")
    else:
        L.append("_No budgets.toml found (see templates/budgets.template.toml)._")
    L.append("")

    L.append("## 26. Power intent (UPF) consistency")
    L.append("")
    intent = load_table(project, "power_intent")
    if len(intent):
        from powermet.intent import render_intent_summary
        L.append("```")
        L.append(render_intent_summary(intent))
        L.append("```")
        bad = intent[~intent["intent_ok"]]
        if len(bad):
            counts = bad["intent_issues"].str.split(";").explode().value_counts()
            L.append("")
            L.append(_md_table(["Issue", "FUB/build entries"], [[k, v] for k, v in counts.items()]))
    else:
        L.append("_No UPF ingested._")
    L.append("")

    L.append("## 27. Engine qualification")
    L.append("")
    if "be_voltus_mw" in df.columns and df["be_voltus_mw"].notna().any():
        try:
            from powermet.qualify import qualify
            q = qualify(df, "be_mw", "be_voltus_mw", cfg.qualify_tolerance_pct)
            m = q.metrics
            L.append(f"`be_voltus_mw` vs reference `be_mw` on {q.scope}: **{q.verdict}** (tolerance MAPE <= {q.tolerance_pct:g}%).")
            L.append("")
            L.append(_md_table(["n", "MAPE", "P50", "P95", "bias", "r"],
                               [[q.n, fmt_pct(m["mape"]), fmt_pct(m["p50_ape"]), fmt_pct(m["p95_ape"]), fmt_pct(q.bias_pct, True), fmt_r(q.r)]]))
        except Exception as exc:
            L.append(f"_Qualification unavailable: {exc}_")
    else:
        L.append("_No second engine ingested (optional `voltus/` source)._")
    L.append("")

    L.append("## 28. Hotspots and inefficiencies")
    L.append("")
    try:
        from powermet.hotspots import hotspots
        for d in sorted(df["design"].astype(str).unique()):
            rep = hotspots(df, d)
            key = "model_root" if "model_root" in rep.table.columns else "fub"
            top = rep.table.head(5)
            L.append(f"**{d} / {rep.build}**" + (f" vs {rep.prev_build}" if rep.prev_build else ""))
            L.append("")
            L.append(_md_table(["FUB", "Power", "Share", "mW/um2", "dPrev", "CG eff", "Flags"],
                               [[r[key], fmt_mw(r["be_mw"]), fmt_pct(r["share_pct"]), f"{r['power_density']:.4f}" if pd.notna(r["power_density"]) else "n/a",
                                 fmt_pct(r["delta_pct"], True) if pd.notna(r["delta_pct"]) else "n/a",
                                 f"{r['cg_efficiency']:.2f}" if "cg_efficiency" in top.columns and pd.notna(r["cg_efficiency"]) else "n/a", r["flags"]]
                                for _, r in top.iterrows()]))
            L.append("")
    except Exception as exc:
        L.append(f"_Hotspot analysis unavailable: {exc}_")
    return L


def _timing_energy_sections(project: Project, cfg: Config, df: pd.DataFrame, meta: dict | None) -> list[str]:
    """Metric trust, timing deltas, power x timing frontier, energy decomposition, compact model."""
    L: list[str] = []
    # ---- 20 metric quality
    L.append("## 20. Metric quality (per-metric trust)")
    L.append("")
    mq = load_table(project, "metric_quality")
    if len(mq):
        L.append(_md_table(["Metric", "Coverage", "r vs BE", "r by build", "Unit conv", "Outliers", "Verdict", "Notes"],
                           [[label(r["metric"]), f"{r['coverage_pct']:.0f}%", fmt_r(r["r_target"]),
                             f"{fmt_r(r['r_min_build'])}..{fmt_r(r['r_max_build'])}" if np.isfinite(r["r_min_build"]) else "n/a",
                             r["unit_conversions"], r["outliers"], r["verdict"], r["notes"]] for _, r in mq.iterrows()]))
        L.append("")
        L.append("A metric is trusted when it is present for nearly every FUB and its association with BE power is stable from build to build; unstable or sparse metrics are candidates for calibration or exclusion.")
    else:
        L.append("_Run `powermet sanitize` to compute per-metric trust._")
    L.append("")

    has_timing = "wns_ps" in df.columns and df["wns_ps"].notna().any()
    # ---- 21 build deltas
    L.append("## 21. Build-to-build power / timing / physical deltas")
    L.append("")
    if has_timing and df["build"].nunique() > 1:
        from powermet.deltas import build_deltas
        for design in sorted(df["design"].astype(str).unique()):
            deltas = build_deltas(df, design)
            if not deltas:
                continue
            d = deltas[-1]
            L.append(f"**{design}: {d.build_from} -> {d.build_to}**  [{d.classification}]")
            L.append("")
            rows = []
            for m in ("be_mw", "wire_cap_pf", "cell_cap_pf", "area"):
                if m in d.totals:
                    rows.append([label(m), f"{d.totals[m][0]:,.1f}", f"{d.totals[m][1]:,.1f}", fmt_pct(d.pct(m), True)])
            if "wns_ps" in d.totals:
                a, b = d.totals["wns_ps"]
                rows.append(["WNS worst partition (ps)", f"{a:+.1f}", f"{b:+.1f}", f"{b - a:+.1f} ps"])
                a, b = d.totals["fmax_ghz"]
                rows.append(["Fmax worst partition (GHz)", f"{a:.3f}", f"{b:.3f}", fmt_pct((b - a) / a * 100, True) if a else "n/a"])
            L.append(_md_table(["Metric", d.build_from, d.build_to, "Change"], rows))
            L.append("")
            if len(d.partition_table):
                from powermet.deltas import classify
                L.append(_md_table(["Partition", "dPower", "dWNS (ps)", "Class"],
                                   [[r["partition"], fmt_pct((r["be_mw_to"] - r["be_mw_from"]) / r["be_mw_from"] * 100, True) if r["be_mw_from"] else "n/a",
                                     f"{r['wns_ps_to'] - r['wns_ps_from']:+.1f}" if np.isfinite(r["wns_ps_to"] - r["wns_ps_from"]) else "n/a",
                                     classify((r["be_mw_to"] - r["be_mw_from"]) / r["be_mw_from"] * 100 if r["be_mw_from"] else 0, r["wns_ps_to"] - r["wns_ps_from"])]
                                    for _, r in d.partition_table.iterrows()]))
                L.append("")
        L.append("Timing is a partition attribute from PrimeTime; FUB power is summed per partition to classify each move as a Pareto improvement, regression, or power-for-performance trade.")
    else:
        L.append("_Requires timing columns (PrimeTime source) and at least two builds._")
    L.append("")

    # ---- 22 frontier
    L.append("## 22. Power x timing frontier")
    L.append("")
    if has_timing:
        from powermet.frontier import frontier
        from powermet.visualization import frontier_chart, plots_available
        perf = load_table(project, "performance")
        pts_all = {}
        for design in sorted(df["design"].astype(str).unique()):
            pts = frontier(df, design, None, None, perf if len(perf) else None)
            pts_all[design] = pts
            L.append(f"**{design}**")
            L.append("")
            L.append(_md_table(["Build", "Power", "Fmax (GHz)", "WNS (ps)", "Pareto", "vs previous"],
                               [[p.build, fmt_mw(p.power_mw), f"{p.fmax_ghz:.3f}" if np.isfinite(p.fmax_ghz) else "n/a",
                                 f"{p.wns_ps:+.1f}" if np.isfinite(p.wns_ps) else "n/a", "*" if p.pareto else "", p.status] for p in pts]))
            L.append("")
        if plots_available():
            try:
                frontier_chart(pts_all, project.reports_dir / "power_timing_frontier.png")
                L.append("![Power x timing frontier](power_timing_frontier.png)")
            except Exception as exc:
                L.append(f"_Frontier chart unavailable: {exc}_")
        else:
            L.append("_Frontier chart not generated (matplotlib unavailable)._")
    else:
        L.append("_Requires timing columns (PrimeTime source)._")
    L.append("")

    # ---- 23 energy decomposition
    L.append("## 23. Energy decomposition (data-movement model)")
    L.append("")
    if meta and "datamove" in (meta.get("features") or {}):
        try:
            from powermet.decomposition import decompose
            from powermet.modeling import DATAMOVE_TERMS
            payload, meta2 = load(project)
            m = payload["models"]["datamove"]
            latest = latest_build_per_design(df)
            sel = df[[b == latest[str(d)] for d, b in zip(df["design"], df["build"].astype(str))]]
            dec = decompose(sel, m)
            L.append("Compact analytical form fitted to BE power (coefficients on physically-motivated terms):")
            L.append("")
            L.append("```")
            L.append("P(FUB) = " + " + ".join(f"{m.coefficients()[t]:.3g} * {t}" for t in m.features) + f" + {m.intercept_:.3g}")
            L.append("```")
            L.append("")
            parts = [DATAMOVE_TERMS[t] for t in m.features if t in DATAMOVE_TERMS]
            keys = [k for k in ("design", "workload", "operating_point") if k in dec.columns]
            g = dec.groupby(keys)[["be_mw", "predicted_mw"] + parts].sum().reset_index()
            rows = []
            for _, r in g.iterrows():
                tot = sum(r[p] for p in parts) or np.nan
                rows.append([r[k] for k in keys] + [fmt_mw(r["be_mw"]), fmt_mw(r["predicted_mw"])] + [fmt_pct(r[p] / tot * 100) for p in parts])
            L.append(_md_table([k.capitalize() for k in keys] + ["BE power", "Predicted"] + [label(p) for p in parts], rows))
            if "pj_per_bit_mm" in dec.columns and dec["pj_per_bit_mm"].notna().any():
                L.append("")
                L.append(f"Data-movement energy coefficient (nominal): {dec['pj_per_bit_mm'].median():.3f} pJ per bit-mm.")
            cvs = (meta.get("cv") or {}).get("summary", {})
            if "datamove" in cvs:
                L.append("")
                L.append(f"Leave-one-build-out MAPE of this compact model: {fmt_pct(cvs['datamove']['mape_mean'])} "
                         f"(baseline {fmt_pct(cvs['baseline']['mape_mean'])}). It uses no FE power estimate, only post-layout features and activity.")
        except Exception as exc:
            L.append(f"_Energy decomposition unavailable: {exc}_")
    else:
        L.append("_Requires a trained data-movement model (bits_per_cycle and avg_net_length_um in the dataset)._")
    L.append("")

    # ---- 24 compact model / integration
    L.append("## 24. Compact model for performance-tool integration")
    L.append("")
    cm = project.models_dir / "compact_power_model.json"
    if cm.exists():
        import json
        doc = json.loads(cm.read_text())
        n_fubs = sum(len(d["fubs"]) for d in doc["designs"].values())
        L.append(f"`{cm.name}`: kind {doc['model_kind']}, {len(doc['designs'])} designs, {n_fubs} FUBs, terms {', '.join(doc['terms']['features'])}. "
                 "Contains per-FUB latest-build physical features, per-workload activity/traffic, operating points, DVFS curve, throughput scaling and the partition timing model.")
        L.append("")
        L.append("Evaluate a workload phase trace with `powermet integrate trace <csv>` or load the JSON in a performance simulator via `powermet.integrate.CompactPowerModel`.")
    else:
        L.append("_Run `powermet model export` to write the compact model, then `powermet integrate trace <csv>`._")
    L.append("")
    return L


def _v1_v3_sections(project: Project, cfg: Config, df: pd.DataFrame, meta: dict | None) -> list[str]:
    """Methodology (V1), predictive-model validation and what-if (V2), workload/exploration (V3)."""
    L: list[str] = []
    # ---- 13 correlation data quality
    L.append("## 13. Correlation data quality (sanitization)")
    L.append("")
    flags = load_table(project, "quality_flags")
    if len(flags):
        n = len(flags)
        usable = int(flags["usable"].sum()) if "usable" in flags.columns else n
        L.append(f"Sanitized dataset in use: {'yes' if sanitized_path(project).exists() and cfg.use_sanitized else 'no'}. "
                 f"{fmt_int(usable)} of {fmt_int(n)} measurements usable ({fmt_pct(usable / n * 100)}).")
        counts = {}
        for fl in flags["quality_flags"].dropna().astype(str):
            for c in fl.split(";"):
                if c:
                    counts[c] = counts.get(c, 0) + 1
        if counts:
            from powermet.sanitize import CHECKS
            L.append("")
            L.append(_md_table(["Check", "Rows", "Blocks use"], [[CHECKS.get(c, (c, False))[0], v, "yes" if CHECKS.get(c, (c, False))[1] else "no"]
                                                                  for c, v in sorted(counts.items(), key=lambda kv: -kv[1])]))
    else:
        L.append("_`powermet sanitize` has not been run; only schema validation was applied._")
    L.append("")

    # ---- 14 lineage
    L.append("## 14. Provenance and lineage")
    L.append("")
    lin = load_table(project, "lineage")
    long = load_table(project, "measurements_long")
    if len(lin):
        ok = int(lin["lineage_ok"].astype(bool).sum())
        L.append(f"Lineage table: {fmt_int(len(lin))} FUB/build entries, {fmt_int(ok)} with a complete FE -> synthesis -> BE -> measurement chain.")
        if len(long):
            src = long.groupby("source").agg(records=("value", "size"), files=("source_file", "nunique"), tool=("tool", "first"),
                                             version=("tool_version", "first")).reset_index()
            L.append("")
            L.append(_md_table(["Source", "Tool", "Version", "Files", "Records"],
                               [[r["source"], r["tool"], r["version"], r["files"], f"{r['records']:,}"] for _, r in src.iterrows()]))
        bad = lin[~lin["lineage_ok"].astype(bool)]
        if len(bad):
            issues = bad["lineage_issues"].str.split(";").explode().value_counts()
            L.append("")
            L.append(_md_table(["Lineage issue", "FUB/build entries"], [[k, v] for k, v in issues.items()]))
        ex = lin[lin["lineage_ok"].astype(bool)].iloc[0] if ok else lin.iloc[0]
        L.append("")
        L.append("Example chain:")
        L.append("")
        L.append("```")
        from powermet.lineage import render_chain
        L.append(render_chain(ex))
        L.append("```")
    else:
        L.append("_No lineage table (dataset imported from a flat file rather than `powermet ingest`)._")
    L.append("")

    # ---- 15 runtime profile
    L.append("## 15. Runtime and memory profile")
    L.append("")
    from powermet.profiling import aggregate_stages, load_profiles
    profs = load_profiles(project, last=50)
    if profs:
        by_cmd: dict[str, dict] = {}
        for pr in profs:
            by_cmd[pr["command"]] = pr      # latest per command
        rows = []
        for cmd, pr in by_cmd.items():
            for st in aggregate_stages(pr["stages"]):
                rows.append([cmd, st["stage"], f"{st['wall_s']:.2f}", f"{st['peak_rss_mb']:.0f}", f"{st['rows']:,}" if st["rows"] else ""])
        L.append(_md_table(["Command", "Stage", "Wall (s)", "Peak RSS (MB)", "Rows"], rows))
        L.append("")
        peak = max(pr["peak_rss_mb"] for pr in by_cmd.values())
        L.append(f"Peak process memory across profiled commands: {peak:.0f} MB. Dataset: {fmt_int(len(df))} rows.")
    else:
        L.append("_No profiles recorded._")
    L.append("")

    # ---- 16 cross-validation
    L.append("## 16. Build-based cross-validation")
    L.append("")
    cv = (meta or {}).get("cv")
    if cv and cv.get("folds"):
        rows = []
        for k in MODEL_ORDER:
            if k in cv["summary"]:
                s_, iv = cv["summary"][k], cv["intervals"][k]
                rows.append([MODEL_NAMES[k], fmt_pct(s_["mape_mean"]), fmt_pct(s_["mape_std"]), fmt_pct(s_["mape_worst"]),
                             fmt_r(s_["r2_mean"]), f"{iv['p05']:+.1f}% .. {iv['p95']:+.1f}%"])
        L.append(f"Leave-one-build-out over {len(cv['folds'])} builds (each build predicted from all others):")
        L.append("")
        L.append(_md_table(["Model", "MAPE mean", "MAPE sd", "MAPE worst", "R^2 mean", "90% error interval"], rows))
        L.append("")
        L.append(_md_table(["Held-out build", "n"] + [MODEL_NAMES[k] for k in MODEL_ORDER if k in cv["folds"][0]["metrics"]],
                           [[f["build"], f["n_test"]] + [fmt_pct(f["metrics"][k]["mape"]) for k in MODEL_ORDER if k in f["metrics"]] for f in cv["folds"]]))
    else:
        L.append("_Not run. Use `powermet model train --cv` or `powermet model validate`._")
    L.append("")

    # ---- 17 what-if example
    L.append("## 17. What-if example")
    L.append("")
    if meta:
        try:
            from powermet.whatif import Override, run_whatif, select_rows
            payload, meta2 = load(project)
            latest = latest_build(df)
            top = df[df["build"].astype(str) == latest].sort_values("be_mw", ascending=False).iloc[0]
            rows = select_rows(df, str(top["design"]), latest, str(top["fub"]),
                               str(top["workload"]) if "workload" in df.columns else None,
                               str(top["operating_point"]) if "operating_point" in df.columns else None)
            res = run_whatif(rows, [Override("wire_cap_pf", "scale", 0.8)], payload, meta2, model_key=cfg.whatif_model)
            cur, prop = float(np.nansum(res.current)), float(np.nansum(res.proposed))
            L.append(f"Largest-power FUB in the latest build ({top['design']} / {latest} / {top['fub']}), wire cap reduced by 20% "
                     f"({MODEL_NAMES[res.model_key]}):")
            L.append("")
            rows_t = [["Predicted BE power", fmt_mw(cur), fmt_mw(prop)], ["Actual BE power", fmt_mw(float(top["be_mw"])), ""],
                      ["Wire cap (pF)", f"{float(rows['wire_cap_pf'].iloc[0]):.3f}", f"{float(rows['wire_cap_pf'].iloc[0]) * 0.8:.3f}"]]
            if res.interval:
                rows_t.append(["90% interval", "", f"{fmt_mw(prop * (1 + res.interval['p05'] / 100))} .. {fmt_mw(prop * (1 + res.interval['p95'] / 100))}"])
            L.append(_md_table(["", "Current", "What-if"], rows_t))
            L.append("")
            L.append(f"Estimated change: {fmt_pct(res.delta_pct, signed=True)}. Reproduce with "
                     f"`powermet model predict --design {top['design']} --fub {top['fub']} --scale wire_cap_pf=0.8`.")
        except Exception as exc:  # report must never fail because of an example
            L.append(f"_What-if example unavailable: {exc}_")
    else:
        L.append("_No trained model._")
    L.append("")

    # ---- 18 workload / energy
    L.append("## 18. Workload, performance and energy per operation")
    L.append("")
    perf = load_table(project, "performance")
    has_wl = "workload" in df.columns and df["workload"].nunique() > 1
    if has_wl or len(perf):
        from powermet.workload import summarize_workloads
        ws = summarize_workloads(df, perf if len(perf) else None)
        rows = []
        for _, r in ws.latest.sort_values(["design", "workload", "operating_point"]).iterrows():
            rows.append([r["design"], r["workload"], r["operating_point"], fmt_mw(r["be_mw"]),
                         f"{r['throughput_gops']:.1f}" if pd.notna(r["throughput_gops"]) else "n/a",
                         f"{r['energy_pj_per_op']:.2f}" if pd.notna(r["energy_pj_per_op"]) else "n/a"])
        L.append("Latest build per design:")
        L.append("")
        L.append(_md_table(["Design", "Workload", "OP", "BE power", "Gops/s", "pJ/op"], rows))
        if ws.perf_model.params:
            L.append("")
            L.append("Throughput scaling exponent b (throughput ~ f^b): " + ", ".join(
                f"{d}/{w}: {b:.2f}" for (d, w), (a, b, r2, n) in sorted(ws.perf_model.params.items())))
        if len(ws.activity_assoc):
            L.append("")
            L.append("Activity vs BE power (Pearson r within design): " + ", ".join(
                f"{r['design']}: {fmt_r(r['r_activity_be'])}" for _, r in ws.activity_assoc.iterrows()))
    else:
        L.append("_Single workload / no performance data; run the V1 ingest on runs with activity/ and perf/ sources._")
    L.append("")

    # ---- 19 exploration example
    L.append("## 19. Design-space exploration example")
    L.append("")
    if meta and len(perf) and "frequency_ghz" in df.columns:
        try:
            from powermet.explore import Explorer
            payload, meta2 = load(project)
            exr = Explorer(df, perf, payload, meta2, model_key=cfg.whatif_model)
            design = str(df["design"].iloc[0])
            wl = default_value(df, "workload", "typical") or "default"
            f0 = float(exr.base_rows(design, wl, None)["frequency_ghz"].iloc[0])
            vals = [round(f0 * k, 2) for k in (0.8, 0.9, 1.1, 1.2)]
            rows = exr.sweep(design, wl, "frequency_ghz", vals)
            L.append(f"Frequency sweep for {design} / {wl} along the fitted DVFS curve:")
            L.append("")
            L.append(_md_table(["Scenario", "f GHz", "V", "BE power", "Gops/s", "pJ/op", "dP", "dE/op", "Pareto"],
                               [[r.scenario, f"{r.frequency_ghz:.2f}", f"{r.voltage_v:.3f}", fmt_mw(r.power_mw),
                                 f"{r.throughput_gops:.1f}" if np.isfinite(r.throughput_gops) else "n/a",
                                 f"{r.energy_pj:.2f}" if np.isfinite(r.energy_pj) else "n/a",
                                 fmt_pct(r.delta_power_pct, True) if r.scenario != "baseline" else "",
                                 fmt_pct(r.delta_energy_pct, True) if r.scenario != "baseline" else "", "*" if r.pareto else ""] for r in rows]))
            L.append("")
            L.append("Reproduce with `powermet explore sweep --design " + design + f" --workload {wl} --param frequency_ghz --values " + ",".join(map(str, vals)) + "`.")
        except Exception as exc:
            L.append(f"_Exploration example unavailable: {exc}_")
    else:
        L.append("_Requires a trained model and performance data._")
    L.append("")
    return L


def write_report(project: Project, cfg: Config, df: pd.DataFrame, make_plots: bool = True) -> Path:
    text = build_report(project, cfg, df, make_plots=make_plots)
    project.reports_dir.mkdir(parents=True, exist_ok=True)
    path = project.reports_dir / REPORT_NAME
    path.write_text(text)
    return path
